In [1]:
%load_ext autoreload
%autoreload 2


import tyssue

In [2]:
from tyssue.core import generation
from tyssue.core.sheet import Sheet

from tyssue.geometry.sheet_geometry import SheetGeometry as sgeom

In [3]:
datasets, specs = generation.three_faces_sheet()
sheet = Sheet('3cells_2D', datasets, specs)
sheet.set_geom('sheet')
sheet.specs['settings']['geometry'] = 'flat'
sgeom.update_all(sheet)

In [4]:

sheet.jv_df

    rho      y is_active    x  basal_shift  z  height
jv
0     0  0.000      True  0.0            4  0      -4
1     0  0.000      True  1.0            4  0      -4
2     0  0.866      True  1.5            4  0      -4
3     0  1.732      True  1.0            4  0      -4
4     0  1.732      True  0.0            4  0      -4
5     0  0.866      True -0.5            4  0      -4
6     0  0.866      True -1.5            4  0      -4
7     0  0.000      True -2.0            4  0      -4
8     0 -0.866      True -1.5            4  0      -4
9     0 -0.866      True -0.5            4  0      -4
10    0 -1.732      True  0.0            4  0      -4
11    0 -1.732      True  1.0            4  0      -4
12    0 -0.866      True  1.5            4  0      -4